server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education_zone
    username: root
    password: parola
    platform: mysql
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  # Hibernate ddl auto (create, create-drop, validate, update)
cors:
  origin: http://localhost:4200

management:
  security:
    enabled: false
# ca sa ne conectam la keycloak
keycloak:
  realm: EducationZone
  resource: Education-zone-client-backend #cum se numeste clientul
  public-client: true
  auth-server-url: http://localhost:8080/auth
  bearer-only: true
  #ssl-required: external
  use-resource-role-mappings: true
  ssl-required: none


  #pentru ca sa ne conectam ca admin sa putem modifica chestii in keycloak (interfata de unde modificam noi manual)
admin-keycloak:
  username: admin
  password: admin
  realm: master
  client: admin-cli
